// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"beards.ly/todo/app"
	"beards.ly/todo/database"
	"beards.ly/todo/dispatcher"
	"beards.ly/todo/repository"
)

// Injectors from wire.go:

func initializeApplication() app.Application {
	postgresConnectionString := database.NewPostgresConnectionString()
	db := database.NewDB(postgresConnectionString)
	userRepository := repository.NewUserRepository(db)
	sender := dispatcher.NewSender(userRepository)
	application := app.NewApplication(sender, db)
	return application
}
